pipeline {
    agent any
    tools { 
      maven 'maven' 
      jdk 'jdk'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './simple-java-maven-app/jenkins/scripts/deliver.sh'
            }
        }
    }
}
