pipeline {
    agent any
    tools {
      maven 'maven'
      jdk 'jdk'
    }
    stages {
        stage("clone code"){
            steps{
               git credentialsId: 'git_credentials', url: 'https://github.com/ravdy/hello-world.git'
            }
        }
        stage("build code"){
            steps{
              sh "mvn clean install"
            }
        }
        stage("deploy"){
            steps{
              echo "Deploy......"
                 
                }
            }
        }
    }
}
